In [4]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (
    train_test_split,
    cross_val_score
)

from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)

from sklearn.linear_model import LinearRegression

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

import joblib

In [5]:
df = pd.read_csv("../dataset/merged_data_cleaned.csv")

df.head()

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,0,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,2,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,3,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0
4,4,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [6]:
print(df.shape)

df.info()

df.describe().T

(1339, 44)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             1339 non-null   int64
 1   Species                1339 non-null   object
 2   Owner                  1332 non-null   object
 3   Country.of.Origin      1338 non-null   object
 4   Farm.Name              980 non-null    object
 5   Lot.Number             276 non-null    object
 6   Mill                   1021 non-null   object
 7   ICO.Number             1180 non-null   object
 8   Company                1130 non-null   object
 9   Altitude               1113 non-null   object
 10  Region                 1280 non-null   object
 11  Producer               1107 non-null   object
 12  Number.of.Bags         1339 non-null   int64
 13  Bag.Weight             1339 non-null   object
 14  In.Country.Partner     1339 non-null   object
 15  Harvest.Year           1292 non-null   object
 16  Grading.Date           1339 non-null   object
 17  Owner.1                1332 non-null   object
 18  Variety                1113 non-null   object
 19  Processing.Method      1169 non-null   object
 20  Aroma                  1339 non-null   float64
 21  Flavor                 1339 non-null   float64
 22  Aftertaste             1339 non-null   float64
 23  Acidity                1339 non-null   float64
 24  Body                   1339 non-null   float64
 25  Balance                1339 non-null   float64
 26  Uniformity             1339 non-null   float64
 27  Clean.Cup              1339 non-null   float64
 28  Sweetness              1339 non-null   float64
 29  Cupper.Points          1339 non-null   float64
 30  Total.Cup.Points       1339 non-null   float64
 31  Moisture               1339 non-null   float64
 32  Category.One.Defects   1339 non-null   int64
 33  Quakers                1338 non-null   float64
 34  Color                  1069 non-null   object
 35  Category.Two.Defects   1339 non-null   int64
 36  Expiration             1339 non-null   object
 37  Certification.Body     1339 non-null   object
 38  Certification.Address  1339 non-null   object
 39  Certification.Contact  1339 non-null   object
 40  unit_of_measurement    1339 non-null   object
 41  altitude_low_meters    1109 non-null   float64
 42  altitude_high_meters   1109 non-null   float64
 43  altitude_mean_meters   1109 non-null   float64
dtypes: float64(16), int64(4), object(24)
memory usage: 460.4+ KB

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,1339.0,669.000000,386.680316,0.0,334.50,669.00,1003.50,1338.00
Number.of.Bags,1339.0,154.182972,129.987162,0.0,14.00,175.00,275.00,1062.00
Aroma,1339.0,7.566706,0.377560,0.0,7.42,7.58,7.75,8.75
Flavor,1339.0,7.520426,0.398442,0.0,7.33,7.58,7.75,8.83
Aftertaste,1339.0,7.401083,0.404463,0.0,7.25,7.42,7.58,8.67
Acidity,1339.0,7.535706,0.379827,0.0,7.33,7.58,7.75,8.75
Body,1339.0,7.517498,0.370064,0.0,7.33,7.50,7.67,8.58
Balance,1339.0,7.518013,0.408943,0.0,7.33,7.50,7.75,8.75
Uniformity,1339.0,9.834877,0.554591,0.0,10.00,10.00,10.00,10.00
Clean.Cup,1339.0,9.835108,0.763946,0.0,10.00,10.00,10.00,10.00
Sweetness,1339.0,9.856692,0.616102,0.0,10.00,10.00,10.00,10.00
Cupper.Points,1339.0,7.503376,0.473464,0.0,7.25,7.50,7.75,10.00
Total.Cup.Points,1339.0,82.089851,3.500575,0.0,81.08,82.50,83.67,90.58
Moisture,1339.0,0.088379,0.048287,0.0,0.09,0.11,0.12,0.28
Category.One.Defects,1339.0,0.479462,2.549683,0.0,0.00,0.00,0.00,63.00
Quakers,1338.0,0.173393,0.832121,0.0,0.00,0.00,0.00,11.00
Category.Two.Defects,1339.0,3.556385,5.312541,0.0,0.00,2.00,4.00,55.00
altitude_low_meters,1109.0,1750.713315,8669.440545,1.0,1100.00,1310.64,1600.00,190164.00
altitude_high_meters,1109.0,1799.347775,8668.805771,1.0,1100.00,1350.00,1650.00,190164.00
altitude_mean_meters,1109.0,1775.030545,8668.626080,1.0,1100.00,1310.64,1600.00,190164.00

In [7]:
# Drop column yang tidak digunakan
drop_columns = [
    "Unnamed: 0",
    "Owner",
    "Farm.Name",
    "Lot.Number",
    "Mill",
    "ICO.Number",
    "Company",
    "Producer",
    "Owner.1",
    "Certification.Address",
    "Certification.Contact",
    "Altitude",
    "Harvest.Year",
    "Grading.Date",
    "Expiration",
    "Certification.Body",
    "In.Country.Partner",
    "Bag.Weight",
    "unit_of_measurement"
]

df = df.drop(columns=drop_columns)

In [8]:
df.head()

,Species,Country.of.Origin,Region,Number.of.Bags,Variety,Processing.Method,Aroma,Flavor,Aftertaste,Acidity,...,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Color,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,Arabica,Ethiopia,guji-hambela,300,NaN,Washed / Wet,8.67,8.83,8.67,8.75,...,8.75,90.58,0.12,0,0.0,Green,0,1950.0,2200.0,2075.0
1,Arabica,Ethiopia,guji-hambela,300,Other,Washed / Wet,8.75,8.67,8.50,8.58,...,8.58,89.92,0.12,0,0.0,Green,1,1950.0,2200.0,2075.0
2,Arabica,Guatemala,NaN,5,Bourbon,NaN,8.42,8.50,8.42,8.42,...,9.25,89.75,0.00,0,0.0,NaN,0,1600.0,1800.0,1700.0
3,Arabica,Ethiopia,oromia,320,NaN,Natural / Dry,8.17,8.58,8.42,8.42,...,8.67,89.00,0.11,0,0.0,Green,2,1800.0,2200.0,2000.0
4,Arabica,Ethiopia,guji-hambela,300,Other,Washed / Wet,8.25,8.50,8.25,8.50,...,8.58,88.83,0.12,0,0.0,Green,2,1950.0,2200.0,2075.0

In [9]:
# Missing value
df.isnull().sum().sort_values(ascending=False)

Color                   270
altitude_mean_meters    230
altitude_high_meters    230
altitude_low_meters     230
Variety                 226
Processing.Method       170
Region                   59
Quakers                   1
Country.of.Origin         1
Cupper.Points             0
Category.Two.Defects      0
Category.One.Defects      0
Moisture                  0
Total.Cup.Points          0
Species                   0
Sweetness                 0
Clean.Cup                 0
Balance                   0
Body                      0
Acidity                   0
Aftertaste                0
Flavor                    0
Aroma                     0
Number.of.Bags            0
Uniformity                0
dtype: int64

In [10]:
df["altitude_category"] = pd.cut(
    df["altitude_mean_meters"],
    bins=[0, 1000, 1500, 2000, np.inf],
    labels=[
        "low",
        "medium",
        "high",
        "very_high"
    ]
)

df[["altitude_mean_meters", "altitude_category"]].head()

df["altitude_category"].value_counts()

df = df.drop(columns=[
    "altitude_low_meters",
    "altitude_high_meters"
])

In [11]:
# Pisahkan feature and target

X = df.drop(columns=["Total.Cup.Points"])
y = df["Total.Cup.Points"]

print("Shape X :", X.shape)
print("Shape y :", y.shape)

Shape X : (1339, 23)
Shape y : (1339,)

In [12]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training :", X_train.shape)
print("Testing  :", X_test.shape)

Training : (1071, 23)
Testing  : (268, 23)

In [13]:
# ceck tipe data
numeric_features = X_train.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("Numerical Features")
print(numeric_features)

print()

print("Categorical Features")
print(categorical_features)

Numerical Features
['Number.of.Bags', 'Aroma', 'Flavor', 'Aftertaste', 'Acidity', 'Body', 'Balance', 'Uniformity', 'Clean.Cup', 'Sweetness', 'Cupper.Points', 'Moisture', 'Category.One.Defects', 'Quakers', 'Category.Two.Defects', 'altitude_mean_meters']

Categorical Features
['Species', 'Country.of.Origin', 'Region', 'Variety', 'Processing.Method', 'Color', 'altitude_category']

In [14]:
# pipeline numeric
numeric_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

In [15]:
# pipeline kategorikal
categorical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)

In [16]:
# gabungkan pipeline
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer,
            numeric_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ]
)

In [17]:
print(numeric_features)

print(categorical_features)

['Number.of.Bags', 'Aroma', 'Flavor', 'Aftertaste', 'Acidity', 'Body', 'Balance', 'Uniformity', 'Clean.Cup', 'Sweetness', 'Cupper.Points', 'Moisture', 'Category.One.Defects', 'Quakers', 'Category.Two.Defects', 'altitude_mean_meters']
['Species', 'Country.of.Origin', 'Region', 'Variety', 'Processing.Method', 'Color', 'altitude_category']

In [18]:
# training
pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ]
)

In [19]:
pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Number.of.Bags', 'Aroma',
                                                   'Flavor', 'Aftertaste',
                                                   'Acidity', 'Body', 'Balance',
                                                   'Uniformity', 'Clean.Cup',
                                                   'Sweetness', 'Cupper.Points',
                                                   'Moisture',
                                                   'Category.One.Defects',
                                                   'Quakers',
                                                   'Category.Two.Defects',
                                                   'altitude_mean_meters']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Species',
                                                   'Country.of.Origin',
                                                   'Region', 'Variety',
                                                   'Processing.Method', 'Color',
                                                   'altitude_category'])])),
                ('model', LinearRegression())])

In [20]:
y_pred = pipeline.predict(
    X_test
)

In [21]:
rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred
    )
)

mae = mean_absolute_error(
    y_test,
    y_pred
)

r2 = r2_score(
    y_test,
    y_pred
)

print("RMSE :", rmse)
print("MAE  :", mae)
print("R²   :", r2)

RMSE : 0.03266717452455296
MAE  : 0.009775876578506742
R²   : 0.9999664944577096

In [22]:
train_r2 = pipeline.score(
    X_train,
    y_train
)

test_r2 = pipeline.score(
    X_test,
    y_test
)

print("Train R² :", train_r2)
print("Test R²  :", test_r2)

Train R² : 0.9999944626645315
Test R²  : 0.9999664944577096

In [23]:
import joblib

joblib.dump(
    pipeline,
    "../model/coffee_model.pkl"
)

print("Model berhasil disimpan!")

Model berhasil disimpan!

In [24]:
loaded_model = joblib.load(
    "../model/coffee_model.pkl"
)

In [25]:
sample = X.iloc[[0]]

In [26]:
prediction = loaded_model.predict(sample)

prediction

array([90.58587925])

In [27]:
import json
from pathlib import Path

In [28]:
options = {
    "species": sorted(df["Species"].dropna().unique().tolist()),
    "country": sorted(df["Country.of.Origin"].dropna().unique().tolist()),
    "region": sorted(df["Region"].dropna().unique().tolist()),
    "variety": sorted(df["Variety"].dropna().unique().tolist()),
    "processing_method": sorted(df["Processing.Method"].dropna().unique().tolist()),
    "color": sorted(df["Color"].dropna().unique().tolist())
}

options

{'species': ['Arabica', 'Robusta'],
 'country': ['Brazil',
  'Burundi',
  'China',
  'Colombia',
  'Costa Rica',
  'Cote d?Ivoire',
  'Ecuador',
  'El Salvador',
  'Ethiopia',
  'Guatemala',
  'Haiti',
  'Honduras',
  'India',
  'Indonesia',
  'Japan',
  'Kenya',
  'Laos',
  'Malawi',
  'Mauritius',
  'Mexico',
  'Myanmar',
  'Nicaragua',
  'Panama',
  'Papua New Guinea',
  'Peru',
  'Philippines',
  'Rwanda',
  'Taiwan',
  'Tanzania, United Republic Of',
  'Thailand',
  'Uganda',
  'United States',
  'United States (Hawaii)',
  'United States (Puerto Rico)',
  'Vietnam',
  'Zambia'],
 'region': ['52 narino (exact location: mattituy; municipal region: florida code 381',
  'acatenango',
  'aceh',
  'aceh gayo',
  'aceh tengah',
  'ada okinawa japan',
  'addis ababa',
  'adolfo lopez mateos',
  'aldea xeucalvitz, ixil region, quiche department',
  'alta paulista (sao paulo)',
  'altotonga',
  'amatenango de la frontera',
  'antigua',
  'antioquia',
  'apaneca',
  'aricha',
  'arusha',
  'arusha meru',
  'asia pacific',
  'ataco, apaneca - ilamatepec mountain range',
  'atitlan',
  'atoyac de alvarez',
  'baihe dist., tainan city 臺南市白河區',
  'bali',
  'bener meriah',
  'benguet, mountain province',
  'berastagi',
  'blend',
  'blida,kercha,guji,oromia',
  'bondowoso',
  'boquete',
  'brazil matas de minas',
  'brunca',
  'bukidnon, mindanao, philppines',
  'bulambuli eastern region',
  'cacahuatique',
  'cajamarca',
  'calnali, hidalgo',
  'campos altos - cerrado',
  'canoas',
  'carmo de minas',
  'cauca',
  'central',
  'central america',
  'central kenya',
  'central region',
  'central valley',
  'cerrado',
  'cerrado - monte carmelo - minas gerais',
  'chamarel (south west)',
  'changhua baguashan 彰化市八卦山',
  'chapadão de ferro (cerrado mineiro)',
  'chapulhuacan, hidalgo',
  'chiang rai',
  'chiang rai thailand',
  'chiangrai',
  'chiapas',
  'chiapas, jaltenango',
  'chiayi alishan 嘉義縣阿里山鄉',
  'chiayi fanlu嘉義縣番路鄉',
  'chickmangalore',
  'chikmagalur',
  'chikmagalur karnataka',
  'chikmagalur karnataka india',
  'chikmagalur karnataka indua',
  'chilón',
  'chocaman, veracruz',
  'chuva, san marcos',
  'cnra station of divo',
  'coatepec',
  'coatepec, coatepec',
  'cofradia de suchitlan',
  'colima',
  'comayagua',
  'comayagua, honduras',
  'cordoba',
  'corillera administrative',
  'coscomatepec',
  'costa rica',
  'cuarenteño',
  'cundinamarca',
  'dala',
  'davao city, region 11',
  'dehong prefecture',
  "department d'artibonite , haiti",
  'department of ahuachapan, municipality of apanecallamatepec mountain',
  'dipilto, nueva segovia',
  'doe kwin, pyin oo lwin',
  'doi chaang village, chiang rai, thialand',
  'dolok sanggul',
  'don duong',
  'dondon, haiti',
  'dongshan dist., tainan city 台南市東山區',
  'dongshan dist., tainan city 臺南市東山區',
  'east java',
  'eastern',
  'eastern highlands province',
  'eastern uganda',
  'eje cafetero',
  'el balsamo, quezaltepec',
  'el desmoronado, talpan de allende jalisco',
  'el paraíso',
  'el progreso',
  'el remudadero',
  'el tumbador, san marcos',
  'escuitla',
  'ethiopia, sidamo',
  'fln mirador',
  'fortín de las flores',
  'gedio',
  'gicumbi',
  'grama valley',
  'guatemala',
  'guayata',
  'guinope el paraíso',
  'guji-hambela',
  'haiti',
  'high mogiana',
  'huanuco',
  'huautla de jimenez',
  'huazalingo, hidalgo',
  'huehuetenango',
  'huila',
  'huila supremo',
  'hustusco',
  'iganga namadrope eastern',
  'ijen',
  'ikand village',
  'iliatenco, guerrero',
  'ilomba vilage, mbozi',
  'indonesia',
  'intibuca',
  'iwala village, mbeya rural',
  'ixhuatlan del cafe',
  'jalapa',
  'jaltenango',
  'jaltocan, hidalgo',
  'jinotega',
  'juchique de ferrer',
  'juquila',
  'kakoma',
  'kapchorwa',
  'kapchorwa eastern',
  'karatu arusha',
  'karatu ngorogoro',
  'karatu northern',
  'kasese',
  'kasese, mt. rwenzori',
  'kayanza',
  'kefa zone, gimbo distict, at a place called woka araba, south west ethiopia.',
  'kelem welega',
  'kenya',
  'kiambu',
  'kilimanjaro',
  'kirinyaga',
  'kona',
  'kwanza norte province, angola',
  'la concordia',
  'la concordia, chiapas',
  'la cumbre',
  'la plata',
  'la reforma, san marcos',
  'la yerba',
  'la yerbabuena',
  'lao p.d.r.',
  'leye, alishan township, chiayi county',
  'leye, alishan township, chiayi county 嘉義阿里山樂野村',
  'limu',
  'lington nihuta',
  'lintong',
  'los angeles',
  'luwero central region',
  'mahuixtlan',
  'mantiqueira de minas',
  'manyara, karatu',
  'manzanillo',
  'marcala',
  'marmelade',
  'matagalpa',
  'matas de minas        ',
  'mbale',
  'mbeya',
  'mbinga',
  'menglian',
  'meru',
  'meru county',
  'mexico',
  'minas gerais, br',
  'mkuu rombo',
  'mmm',
  'mogiana',
  'monte carmelo',
  'moshi',
  'motozintla',
  'motozintla, chiapas',
  'mountain ali, taiwan',
  'mountains of minas gerais',
  'mt elgon',
  'mt. rwenzori',
  'mubuyu estate',
  'mumirwa',
  'muranga',
  'mzuzu',
  'nantou',
  'nanxi dist., tainan city 臺南市楠西區',
  'naranjo',
  'nariño',
  'natou county',
  'nayarit',
  'new taipei zhonghe 新北市中和區',
  'ngorogoro',
  'nkure- meru',
  'norte',
  'northern',
  'nueva segovia',
  'nuevo oriente',
  'nyeri',
  'oaxaca',
  'occidental',
  'occidente',
  'ocosingo',
  'ocotepeque',
  'ohuapan, tlaltetela',
  'oldeani , mongola',
  'orient',
  'oriente',
  'oromia',
  'oromiya',
  'paksong,laos',
  'pasto',
  'penachi, cecanor',
  'pereira',
  'peru',
  'petatlan',
  'phahi',
  'pitalito',
  'pluma hidalogo, oaxaca',
  'pochutla',
  'progreso santa rosa teocelo',
  'province of manabi, ecuador',
  'puno',
  'pyin oo lwin',
  'pyinoolwin',
  'quetzaltenango',
  'ruvuma',
  'ruvuma, mbinga',
  'sacatepequez, guatemala',
  'sacún palma, municipio de chilón, chiapas',
  'san bartolo tutotepec',
  'san fernando',
  'san ignacio',
  'san isidro',
  'san juan, playas',
  'san lucas toliman, solola',
  'san marcos',
  'san miguel del puerto',
  'san pedro cotzilnam',
  'san rafael',
  'san ramon',
  'santa ana',
  'santa catarina juquila',
  'santa maria sitepec',
  'santa rosa',
  'santander',
  'santo domingo cacalotepec',
  'santo reyes nopala',
  'sapan toraja',
  'sheema south western',
  'shizingo village',
  'sidamo',
  'sierra alta mixe y zapoteca',
  'sierra fraylesca, chiapas',
  'sierra madre occidental',
  'sierra norte yajalon, chiapas',
  'sierra, chiapas',
  'siguatepeque, comayagua',
  'siltepec el triunfo',
  'siltepec el triunfo, chiapas, mexico',
  'sipi, mt elgon',
  'snnp/kaffa zone,gimbowereda',
  'snnprg; kafa; telo woreda; shada kebele',
  'solola',
  'south huila',
  'south of minas',
  'south western',
  'southern',
  'southern- zomba',
  'sul de minas',
  'sul de minas - carmo de minas',
  'sulawesi',
  'sumatra brastagi',
  'taichung taiping 台中市太平區',
  'taichung xinshe 台中市新社區',
  'taiwan',
  'taiwu township , pingtung county 屏東縣泰武鄉',
  'talpa de allende',
  'tapachula',
  'tarrazu',
  'temanggung, indonesia',
  'temaxcalapa',
  'tenango de doria, hidalgo',
  'tepetzingo',
  'tepictla',
  'test',
  'thailand',
  'thiotte, haiti',
  'tlacuilotepec',
  'tlanchinol, hidalgo',
  'tlatlauquitepec',
  'tolima',
  'totutla',
  'tres rios',
  'turrialba',
  'tuxtla gutierrez',
  'vale da grama',
  'valle central',
  'veracruz',
  'vietnam',
  'vietnam cau dat',
  'vietnam tutra',
  'villa talea de castro',
  'west and central valley',
  'west nile',
  'west valley',
  'western',
  'western region',
  'xalapa',
  'xicotepec de juarez',
  'xishuangbanna prefecture',
  'xochitonalco, huautla        ',
  'yajalon',
  'yauco region',
  'yauk sauk, shan state',
  'yecuatla',
  'yirgacheffe',
  'yunlin gukeng he bao 雲林縣古坑鄉荷苞村',
  'yunlin 雲林縣石壁',
  'yunnan',
  'ywar ngan',
  'ywar ngan township',
  'zapotitlan de mendez',
  'zaragoza itundujia',
  'zentla',
  'zihuatanejo de azueta',
  '南投國姓',
  '古坑鄉荷包村尖山坑60號',
  '台中和平區',
  '台中新社',
  '台南市東山區 (dongshan dist., tainan city)',
  '台南市東山區( dongshan dist., tainan city)',
  '台東太麻里',
  '台灣',
  '嘉義阿里山',
  '國姓鄉 guoshing township',
  '苗栗三灣',
  '苗栗泰安'],
 'variety': ['Arusha',
  'Blue Mountain',
  'Bourbon',
  'Catimor',
  'Catuai',
  'Caturra',
  'Ethiopian Heirlooms',
  'Ethiopian Yirgacheffe',
  'Gesha',
  'Hawaiian Kona',
  'Java',
  'Mandheling',
  'Marigojipe',
  'Moka Peaberry',
  'Mundo Novo',
  'Other',
  'Pacamara',
  'Pacas',
  'Pache Comun',
  'Peaberry',
  'Ruiru 11',
  'SL14',
  'SL28',
  'SL34',
  'Sulawesi',
  'Sumatra',
  'Sumatra Lintong',
  'Typica',
  'Yellow Bourbon'],
 'processing_method': ['Natural / Dry',
  'Other',
  'Pulped natural / honey',
  'Semi-washed / Semi-pulped',
  'Washed / Wet'],
 'color': ['Blue-Green', 'Bluish-Green', 'Green']}

In [29]:
statistics = {
    "dataset": "Coffee Quality Database from CQI",
    "problem_type": "Regression",
    "algorithm": "Linear Regression",
    "target": "Total.Cup.Points",

    "total_records": len(df),
    "total_features": X.shape[1],

    "train_size": len(X_train),
    "test_size": len(X_test),

    "rmse": float(rmse),
    "mae": float(mae),
    "r2": float(r2),

    "train_r2": float(train_r2),
    "test_r2": float(test_r2)
}

statistics

{'dataset': 'Coffee Quality Database from CQI',
 'problem_type': 'Regression',
 'algorithm': 'Linear Regression',
 'target': 'Total.Cup.Points',
 'total_records': 1339,
 'total_features': 23,
 'train_size': 1071,
 'test_size': 268,
 'rmse': 0.03266717452455296,
 'mae': 0.009775876578506742,
 'r2': 0.9999664944577096,
 'train_r2': 0.9999944626645315,
 'test_r2': 0.9999664944577096}

In [30]:
ROOT_DIR = Path.cwd().parent

ASSETS_DIR = ROOT_DIR / "assets"

ASSETS_DIR.mkdir(exist_ok=True)

In [31]:
with open(
    ASSETS_DIR / "options.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        options,
        f,
        indent=4,
        ensure_ascii=False
    )

In [32]:
with open(
    ASSETS_DIR / "statistics.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        statistics,
        f,
        indent=4,
        ensure_ascii=False
    )